name: Build Android APK & Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create a release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install flet
          pip install -r requirements.txt

      - name: Build APK
        run: |
          flet build apk

      - name: Get changelog for release body
        id: get_changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --latest --strip all

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/apk/*.apk
          body: ${{ steps.get_changelog.outputs.content }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}